version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
    depends_on:
      - db
  db:
    image: sqlserver
    environment:
      - SA_PASSWORD: "P@ssw0rd123!"
      - ACCEPT_EULA: "Y"