version: '3'

services:
  jekyll: 
    image: jekyll/jekyll:3.7
    container_name: myblog-com
    environment:
        - JEKYLL_ENV=docker
    # force_polling makes the linux box watch for any changes to files, then it will regenerate
    # livereload gets the browser to automatically refresh when changes happen to files
    command: jekyll serve --force_polling --livereload
    ports:
        - 4000:4000
        - 3000:3000
        - 35729:35729
    volumes:
        - $PWD/blog:/srv/jekyll
        - $PWD/vendor/bundle:/usr/local/bundle