// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace TaxApp.Data.TaxesDb
{

    // Address
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.1.0")]
    public partial class AddressConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Address>
    {
        public AddressConfiguration()
            : this("dbo")
        {
        }

        public AddressConfiguration(string schema)
        {
            ToTable(schema + ".Address");
            HasKey(x => x.SalesOrderId);

            Property(x => x.SalesOrderId).HasColumnName(@"SalesOrderId").IsRequired().HasColumnType("uniqueidentifier").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Address1).HasColumnName(@"Address1").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(150);
            Property(x => x.Address2).HasColumnName(@"Address2").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(150);
            Property(x => x.City).HasColumnName(@"City").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.State).HasColumnName(@"State").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(10);
            Property(x => x.Zip).HasColumnName(@"Zip").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(14);

            // Foreign keys
            HasRequired(a => a.SalesOrder).WithOptional(b => b.Address).WillCascadeOnDelete(false); // FK_Address_SalesOrder
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
