// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace TaxApp.Data.TaxesDb
{

    // Address
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.1.0")]
    public partial class Address
    {
        public System.Guid SalesOrderId { get; set; } // SalesOrderId (Primary key)
        public string Address1 { get; set; } // Address1 (length: 150)
        public string Address2 { get; set; } // Address2 (length: 150)
        public string City { get; set; } // City (length: 50)
        public string State { get; set; } // State (length: 10)
        public string Zip { get; set; } // Zip (length: 14)

        // Foreign keys
        public virtual SalesOrder SalesOrder { get; set; } // FK_Address_SalesOrder

        public Address()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
