// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace TaxApp.Data.TaxesDb
{

    // SalesOrderLineItem
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.1.0")]
    public partial class SalesOrderLineItemConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SalesOrderLineItem>
    {
        public SalesOrderLineItemConfiguration()
            : this("dbo")
        {
        }

        public SalesOrderLineItemConfiguration(string schema)
        {
            ToTable(schema + ".SalesOrderLineItem");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").IsRequired().HasColumnType("uniqueidentifier").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SalesOrderId).HasColumnName(@"SalesOrderId").IsRequired().HasColumnType("uniqueidentifier");
            Property(x => x.Quantity).HasColumnName(@"Quantity").IsRequired().HasColumnType("int");
            Property(x => x.Price).HasColumnName(@"Price").IsRequired().HasColumnType("decimal").HasPrecision(18,2);
            Property(x => x.LineTotal).HasColumnName(@"LineTotal").IsRequired().HasColumnType("decimal").HasPrecision(18,2);
            Property(x => x.Product).HasColumnName(@"Product").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(200);

            // Foreign keys
            HasRequired(a => a.SalesOrder).WithMany(b => b.SalesOrderLineItems).HasForeignKey(c => c.SalesOrderId).WillCascadeOnDelete(false); // FK_SalesOrderLineItem_SalesOrder
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
