// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace TaxApp.Data.TaxesDb
{

    // SalesOrder
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.1.0")]
    public partial class SalesOrderConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SalesOrder>
    {
        public SalesOrderConfiguration()
            : this("dbo")
        {
        }

        public SalesOrderConfiguration(string schema)
        {
            ToTable(schema + ".SalesOrder");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").IsRequired().HasColumnType("uniqueidentifier").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SubTotal).HasColumnName(@"SubTotal").IsRequired().HasColumnType("decimal").HasPrecision(18,2);
            Property(x => x.Tax).HasColumnName(@"Tax").IsRequired().HasColumnType("decimal").HasPrecision(18,2);
            Property(x => x.Total).HasColumnName(@"Total").IsRequired().HasColumnType("decimal").HasPrecision(18,2);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
