// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace TaxApp.Data.TaxesDb
{

    // SalesOrder
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.1.0")]
    public partial class SalesOrder
    {
        public System.Guid Id { get; set; } // Id (Primary key)
        public decimal SubTotal { get; set; } // SubTotal
        public decimal Tax { get; set; } // Tax
        public decimal Total { get; set; } // Total

        // Reverse navigation
        public virtual Address Address { get; set; } // Address.FK_Address_SalesOrder
        public virtual System.Collections.Generic.ICollection<SalesOrderLineItem> SalesOrderLineItems { get; set; } // SalesOrderLineItem.FK_SalesOrderLineItem_SalesOrder

        public SalesOrder()
        {
            SalesOrderLineItems = new System.Collections.Generic.List<SalesOrderLineItem>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
