// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace TaxApp.Data.TaxesDb
{

    // StateTax
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.1.0")]
    public partial class StateTaxConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<StateTax>
    {
        public StateTaxConfiguration()
            : this("dbo")
        {
        }

        public StateTaxConfiguration(string schema)
        {
            ToTable(schema + ".StateTax");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").IsRequired().HasColumnType("uniqueidentifier").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.State).HasColumnName(@"State").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(10);
            Property(x => x.TaxPercent).HasColumnName(@"TaxPercent").IsRequired().HasColumnType("decimal").HasPrecision(12,8);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
